version: "3.4"

services:
  server-dev:
    build:
      context: ./
      dockerfile: ./dockerfile
    image: obs-server
    ports:
      - 5900:5900
    container_name: obs-server
    environment:
      - VNC_PASSWORD=mypassword
    command: bash -c "tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

